### ISSUE TITLE
source maps: errors must refer to the original source

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-PL/babel-tanhauhau#24]
@AdrianMoraRodriguez @PSantanaGlez13 

We need to implement source maps:  errors must refer to the original source

**Comment by AdrianMoraRodriguez** [comment]
I've been testing and, indeed, Babel by default creates source maps, for this you have to perform a series of steps:  
1. In the babel.config.json you have to put the option “sourceMaps”: “both”  
2. When transpiling with Babel use the option --outdir-dir  
3. Execute the output file of the directory indicated with node --enable-source-maps  

This last option is only to execute but with the first two steps the source map is already generated. eg:
With the following code:
```js
let a = [1,2,3, else x => {throw new Error("Undefined value")}];
console.log(a[3]); // Should throw an error
a.push(5);
console.log(a[3]);
```
Without a sourcemap the error is:
```
[stdin]:5
  throw new Error("Undefined value");
  ^

Error: Undefined value
    at DefaultVector.fn ([stdin]:5:9)
    at Object.get (/Users/adrian/Desktop/Clases/Cuarto/segundo_cuatri/TFG/pruebas_de_instalacion/node_modules/@ull-esit-pl/babel-plugin-default-vector/src/support.js:23:31)
    at [stdin]:7:14
    at runScriptInThisContext (node:internal/vm:209:10)
    at node:internal/process/execution:449:12
    at [stdin]-wrapper:6:24
    at runScriptInContext (node:internal/process/execution:447:60)
    at evalFunction (node:internal/process/execution:280:30)
    at evalTypeScript (node:internal/process/execution:292:3)
    at node:internal/main/eval_stdin:51:5

Node.js v23.7.0
```
But, if I run:

```bash
npx babel src --out-dir lib --source-maps
node --enable-source-maps lib/prueba.js
```
The new error generated is:
```
/Users/adrian/Desktop/Clases/Cuarto/segundo_cuatri/TFG/pruebas_de_instalacion/src/prueba.js:1
let a = [1,2,3, else x => {throw new Error("Undefined value")}];
                           ^


Error: Undefined value
    at x (/Users/adrian/Desktop/Clases/Cuarto/segundo_cuatri/TFG/pruebas_de_instalacion/src/prueba.js:1:34)
    at Object.get (/Users/adrian/Desktop/Clases/Cuarto/segundo_cuatri/TFG/pruebas_de_instalacion/node_modules/@ull-esit-pl/babel-plugin-default-vector/src/support.js:23:31)
    at Object.<anonymous> (/Users/adrian/Desktop/Clases/Cuarto/segundo_cuatri/TFG/pruebas_de_instalacion/src/prueba.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1723:14)
    at Object..js (node:internal/modules/cjs/loader:1888:10)
    at Module.load (node:internal/modules/cjs/loader:1458:32)
    at Function._load (node:internal/modules/cjs/loader:1275:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)

Node.js v23.7.0
```
As can be seen, the new error is on the original code, which is the desired one

**Comment by crguezl** [comment]
👏 👏 Wow!!! ¡Thank you @AdrianMoraRodriguez ! 🔥

**Comment by crguezl** [comment]
What a head I have!

We already have s.t  about it  in our own notes:  https://github.com/ULL-ESIT-PL/babel-learning/blob/main/src/babel-tutorial/README.md. I added a link to this issue in the references.
